"""
TORA Research Subsystem (Phase 2H-A, 2H-B, 2H-C, 2H-D & 2H-E)
Unified, provider-agnostic research abstraction with search normalization,
safe web fetching, deterministic evidence extraction, source verification,
and multi-source synthesis & corroboration.
"""

from .models import (
    SourceMetadata,
    SearchResult,
    FetchResult,
    SearchResponse,
    FetchedPage,
    ExtractedClaim,
    ResearchEvidence,
    SourceType,
    AuthorityLevel,
    VerificationStatus,
    FreshnessStatus,
    ConfidenceLevel,
    SourceCredibility,
    VerifiedClaim,
    ClaimConflict,
    VerifiedResearchEvidence,
    SourceRelationship,
    AgreementStatus,
    CorroborationStrength,
    ClaimSemanticSignature,
    ResearchClaimGroup,
    ClaimAgreement,
    SynthesisConclusion,
    ResearchSynthesis,
    current_utc_timestamp,
    extract_domain_from_url,
)
from .exceptions import (
    ResearchError,
    ResearchSearchError,
    ResearchFetchError,
    ResearchValidationError,
    ResearchProviderError,
)
from .normalization import (
    SearchNormalizer,
    normalize_url,
    clean_text,
    validate_search_query,
    TRACKING_PARAMS,
    MAX_TITLE_LENGTH,
    MAX_SNIPPET_LENGTH,
    MAX_QUERY_LENGTH,
    DEFAULT_MAX_RESULTS,
    HARD_MAX_RESULTS,
)
from .evidence import (
    EvidenceExtractor,
    extract_financial_entities,
)
from .credibility import (
    SourceVerifier,
    evaluate_freshness,
    check_lookalike_domain,
    matches_domain,
    REGULATOR_DOMAINS,
    OFFICIAL_BANK_DOMAINS,
    ESTABLISHED_MEDIA_DOMAINS,
    SECONDARY_AGGREGATOR_DOMAINS,
)
from .synthesis import (
    ResearchSynthesizer,
    create_claim_signature,
    extract_entity_from_claim,
    extract_product_from_claim,
)
from .provider import (
    ResearchProvider,
    CompositeResearchProvider,
    MAX_RESEARCH_QUERY_LENGTH,
    MAX_RESEARCH_URL_LENGTH,
    DEFAULT_RESEARCH_MAX_RESULTS,
    MAX_RESEARCH_RESULTS_LIMIT,
    DEFAULT_RESEARCH_MAX_CHARS,
)
from .factory import get_research_provider

__all__ = [
    "SourceMetadata",
    "SearchResult",
    "FetchResult",
    "SearchResponse",
    "FetchedPage",
    "ExtractedClaim",
    "ResearchEvidence",
    "SourceType",
    "AuthorityLevel",
    "VerificationStatus",
    "FreshnessStatus",
    "ConfidenceLevel",
    "SourceCredibility",
    "VerifiedClaim",
    "ClaimConflict",
    "VerifiedResearchEvidence",
    "SourceRelationship",
    "AgreementStatus",
    "CorroborationStrength",
    "ClaimSemanticSignature",
    "ResearchClaimGroup",
    "ClaimAgreement",
    "SynthesisConclusion",
    "ResearchSynthesis",
    "current_utc_timestamp",
    "extract_domain_from_url",
    "ResearchError",
    "ResearchSearchError",
    "ResearchFetchError",
    "ResearchValidationError",
    "ResearchProviderError",
    "SearchNormalizer",
    "normalize_url",
    "clean_text",
    "validate_search_query",
    "TRACKING_PARAMS",
    "MAX_TITLE_LENGTH",
    "MAX_SNIPPET_LENGTH",
    "MAX_QUERY_LENGTH",
    "DEFAULT_MAX_RESULTS",
    "HARD_MAX_RESULTS",
    "EvidenceExtractor",
    "extract_financial_entities",
    "SourceVerifier",
    "evaluate_freshness",
    "check_lookalike_domain",
    "matches_domain",
    "REGULATOR_DOMAINS",
    "OFFICIAL_BANK_DOMAINS",
    "ESTABLISHED_MEDIA_DOMAINS",
    "SECONDARY_AGGREGATOR_DOMAINS",
    "ResearchSynthesizer",
    "create_claim_signature",
    "extract_entity_from_claim",
    "extract_product_from_claim",
    "ResearchProvider",
    "CompositeResearchProvider",
    "MAX_RESEARCH_QUERY_LENGTH",
    "MAX_RESEARCH_URL_LENGTH",
    "DEFAULT_RESEARCH_MAX_RESULTS",
    "MAX_RESEARCH_RESULTS_LIMIT",
    "DEFAULT_RESEARCH_MAX_CHARS",
    "get_research_provider",
]
